### ISSUE TITLE
Can't find webgpu_xros.h

### ISSUE THREAD

**Issue by PZerua** [blitz-research/dawnxr#1]
Hi!

I found your Dawn fork with openxr support, and I'm currently trying to compile your dawnxr lib to give it a try. I've succesfully compiled and linked Dawn, but I can't find the file webgpu_xros.h anywhere, am I missing something?

Thanks!

**Comment by blitz-research** [comment]
Oops, that shouldn't be there sorry. I've removed it and tweaked the README a bit as it was way out of date.

You'll need to use the 'openxr' branch of this fork of dawn: https://github.com/blitz-research/dawn

I've just added a release containing a prebuilt static lib for windows.

If you're using D3D12 dawn backend, you should be able to use the dawnxr OpenXR backend the way you would any other.

If you're using the Vulkan dawn backend, you'll also need use the slightly messier dawnxr::createAdapterDiscoveryOptions() function to create an 'OpenXR compatible' dawn device first. I recommend using this anyway even if you're only creating a D3D12 backend, as it may do more on other backends in future.

**Comment by PZerua** [comment]
Thanks a lot! Already managed to build everything and connect your Dawn branch and OpenXR :)

My Oculus 2 is detected but I haven't managed to render anything yet, just a black screen. One thing I noticed is that in the WebGPU samples there is always a ``wgpu::SwapChainPresent(swapchain);`` (swapchain of type ``wgpu::SwapChain``) to render to the screen, but in your dawnxr what is returned in ``createSwapchain()`` are of type ``webgpu::TextureView``. Is ``SwapChainPresent`` not needed now? Probably I should check more WebGPU and OpenXR tutorials.

**Comment by blitz-research** [comment]
> Is SwapChainPresent not needed now?

This is correct, when using OpenXR, OpenXR does all the swapchain stuff, including creating the swap chain and presenting it.

Everything else is the same though. You use the OpenXR swap chain texture view to initialize a RenderPassColorAttachment when creating a RenderPassEncoder, the same way you would use a non-OpenXR swap chains's GetCurrentTextureView().

Cool that it sounds like it works (or at least doesn't not work yet!) on Oculus 2. I have a Vive and have only ever tested on that.
